### PR TITLE
Jsdoc support

### PR DESCRIPTION
**Pull request by ankitskvmdam**
add jsdoc to the project.

### CODE REVIEW

**Review by yochannah — CHANGES_REQUESTED** [review]
@ankitskvmdam this looks great, but a couple of comments before we can merge: 

1. when I run npm run generate-docs, I get this message: `ENOENT: no such file or directory, open './readme.md'`
2. It would be nice to add the npm run command to the readme :)

**Comment by yochannah** [comment]
@ankitskvmdam let me know when this is ready to re-review :)

**Comment by ankitskvmdam** [comment]
It is ready to re-review. 👍

**Review by yochannah — APPROVED** [review]

**Comment by yochannah** [comment]
You are a star :star:

**Pull request merged**
